services:
  express:
    build:
      context: ./
    volumes:
      - ./src:/app/src
  redis:
    image: redis
    ports:
      - 6379:6379    
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/user_conf.d
    
  uploader:
    build:
      context: ./uploader