services:
  server:
    build:
      context: ./
    ports:
      - 80:3000
    volumes:
      - ./src:/app/src
  redis:
    image: redis
    ports:
      - 6379:6379    
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf